# # Install pre-commit hooks via
# pre-commit install

- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.30.0
  hooks:
  # yapf = yet another python formatter
  - id: yapf
    name: yapf
    types: [python]
    exclude: >
      (?x)^(
          docs/.*|
      )$
    args: ['-i']

- repo: local
  hooks:
  # yapf = yet another python formatter

  # prospector: collection of linters
  - id: pylint
    language: system
    types: [file, python]
    name: pylint
    entry: pylint
