[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable = [
    "too-many-ancestors",
    "R0801",
]
module-naming-style="any"

[tool.pytest.ini_options]
python_files = "test_*.py example_*.py"
python_functions = example_* test_*
filterwarnings = [
    "ignore::DeprecationWarning:aiida:",
    "ignore::DeprecationWarning:plumpy:",
    "ignore::DeprecationWarning:django:",
    "ignore::DeprecationWarning:frozendict:",
    "ignore::DeprecationWarning:sqlalchemy:",
    "ignore::DeprecationWarning:yaml:",
    "ignore::DeprecationWarning:pymatgen:",
]
