name: CI

on: [push, pull_request]

jobs:

  tests:
    name: Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[tests]

      - name: Run test suite
        run: pytest

  examples:
    name: Run examples
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build #and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          tags: aiida_raspa_test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run examples
        run: |  # Examples stored and copied from .github/workflows/run_examples.sh
          export DOCKERID=`docker run -d aiida_raspa_test`
          docker exec --tty $DOCKERID wait-for-services
          docker logs $DOCKERID
          docker exec --tty --user aiida $DOCKERID /bin/bash -l -c 'cd $HOME; bash run_examples.sh'

  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[pre-commit,tests,docs]

      - name: Run pre-commit
        run: |
          pre-commit install
          pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[docs]

      - name: Build docs
        run: |
          make -C docs html
